version: "3.9"

services:
  postgres_db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=fastapi_test_db
      - POSTGRES_USER=fastapi_test
      - POSTGRES_PASSWORD=fastapi_test_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  app:
    build:
      context: ./
    depends_on:
      - postgres_db
    restart: unless-stopped
    container_name: app
    ports:
      - 8000:8000
  
 
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring

volumes:
  postgres_data:



